plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.hadaf.hadafnative'
version = '1.0.0'

android {
  namespace "com.hadaf.hadafnative"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'com.google.android.gms:play-services-auth:20.7.0'
}
